export const interdimensionalPulseLottie = {
  v: '5.7.4',
  fr: 60,
  ip: 0,
  op: 240,
  w: 512,
  h: 512,
  nm: 'Interdimensional Pulse',
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: 'Outer Ring',
      sr: 1,
      ks: {
        o: { a: 0, k: 100 },
        r: { a: 0, k: 0 },
        p: { a: 0, k: [256, 256, 0] },
        a: { a: 0, k: [0, 0, 0] },
        s: { a: 0, k: [100, 100, 100] },
      },
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'el',
              p: { a: 0, k: [0, 0] },
              s: {
                a: 1,
                k: [
                  { t: 0, s: [160, 160], e: [320, 320] },
                  { t: 120, s: [320, 320], e: [160, 160] },
                  { t: 240, s: [160, 160] },
                ],
              },
              d: 1,
              nm: 'Ellipse Path 1',
            },
            {
              ty: 'st',
              c: { a: 0, k: [0.19, 0.91, 0.98, 1] },
              o: {
                a: 1,
                k: [
                  { t: 0, s: [15], e: [85] },
                  { t: 120, s: [85], e: [15] },
                  { t: 240, s: [15] },
                ],
              },
              w: { a: 0, k: 10 },
              lc: 2,
              lj: 2,
              nm: 'Stroke 1',
            },
            {
              ty: 'tm',
              s: { a: 0, k: 0 },
              e: {
                a: 1,
                k: [
                  { t: 0, s: [30], e: [95] },
                  { t: 120, s: [95], e: [30] },
                  { t: 240, s: [30] },
                ],
              },
              o: {
                a: 1,
                k: [
                  { t: 0, s: [0], e: [360] },
                  { t: 240, s: [360] },
                ],
              },
              m: 1,
              nm: 'Trim Paths 1',
            },
            {
              ty: 'tr',
              p: { a: 0, k: [0, 0] },
              a: { a: 0, k: [0, 0] },
              s: { a: 0, k: [100, 100] },
              r: { a: 0, k: 0 },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
              nm: 'Transform',
            },
          ],
          nm: 'Ring Group',
        },
      ],
      ip: 0,
      op: 240,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 4,
      nm: 'Core Glow',
      sr: 1,
      ks: {
        o: {
          a: 1,
          k: [
            { t: 0, s: [35], e: [85] },
            { t: 80, s: [85], e: [35] },
            { t: 160, s: [35], e: [85] },
            { t: 240, s: [85] },
          ],
        },
        r: { a: 0, k: 0 },
        p: { a: 0, k: [256, 256, 0] },
        a: { a: 0, k: [0, 0, 0] },
        s: {
          a: 1,
          k: [
            { t: 0, s: [80, 80], e: [125, 125] },
            { t: 120, s: [125, 125], e: [80, 80] },
            { t: 240, s: [80, 80] },
          ],
        },
      },
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'el',
              p: { a: 0, k: [0, 0] },
              s: { a: 0, k: [90, 90] },
              d: 1,
              nm: 'Ellipse Path 1',
            },
            {
              ty: 'fl',
              c: { a: 0, k: [0.72, 0.94, 1, 1] },
              o: { a: 0, k: 100 },
              r: 1,
              nm: 'Fill 1',
            },
            {
              ty: 'tr',
              p: { a: 0, k: [0, 0] },
              a: { a: 0, k: [0, 0] },
              s: { a: 0, k: [100, 100] },
              r: { a: 0, k: 0 },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
              nm: 'Transform',
            },
          ],
          nm: 'Core Group',
        },
      ],
      ip: 0,
      op: 240,
      st: 0,
      bm: 0,
    },
  ],
} as const
